### ISSUE TITLE
Formulation correctness question

### ISSUE THREAD

**Issue by odow** [lanl-ansi/rosetta-opf#14]
@adow031 asks

![image](https://user-images.githubusercontent.com/8177701/172989712-7f38523a-4f86-4b85-bd9c-3df471cb74a9.png)

https://github.com/lanl-ansi/rosetta-opf/blob/09e76f505c04cc788256a4f3f479033ba6abe1f0/jump.jl#L86-L91

This isn't my wheelhouse, but I assume @ccoffrin checked this pretty thoroughly?

**Comment by ccoffrin** [comment]
I double checked this and the math is correct, although I agree the style could be improved. 

The `tm` term is one directional (it is the voltage scaler in a transformer) and rescales the `vm_fr` variable. It is omitted in any expression where there is `vm_to` only, the only such case is the one you highlight.

For style improvements I will fix the reversed terms in the cosine argument and I am also going to rename `tm` to `tm2` so that the value of `tm` here is not different than what is currently used in PowerModels.

**Comment by adow031** [comment]
Thanks for taking a look at this. Just one last question: if is the voltage magnitude at the sending bus is needing to be scaled by tm (now ttm), why is vm_fr${}^2$ not being scaled by ttm${}^2$?

**Comment by ccoffrin** [comment]
`ttm` is `tm^2` so it already includes the square that goes with `vm_fr^2`.

Maybe a follow up question would be then why not have `tm` on the expressions that have `vm_fr`?  This follows from how you convert the complex expression `conj(Y)/T*V_fr*conj(V_to))` into real valued expressions with `Y` and `T` in rectangular coordinates and `V` in polar coordinates.   If you do a similar expansion but with `T` in polar coordinates then it will match exactly the rule of one `tm` per each `vm_fr`.  You can see that expansion here, https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/form/acp.jl#L296-L334

You might also find these explanations interesting which do all of `V`,`T`,`Y` in rectangular coordinates, 
https://github.com/lanl-ansi/rosetta-opf/blob/main/variants/jump-rectangular-real.jl
https://github.com/lanl-ansi/rosetta-opf/blob/main/variants/jump-rectangular-complex.jl

**Comment by adow031** [comment]
Thanks for your time and explanation.

**Comment by ccoffrin** [comment]
No problem any time!
